// <auto-generated />
using System;
using Labb1_MinimalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1_MinimalAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230913165622_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1_MinimalAPI.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLoanAble")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("973a03e1-d0b0-423b-aab3-a3b4698deaa7"),
                            Author = "Tobias",
                            Description = "Very Spooky",
                            Genre = "Spooky",
                            IsLoanAble = true,
                            Title = "Spooky Book",
                            Year = new DateTime(2023, 9, 13, 18, 56, 21, 929, DateTimeKind.Local).AddTicks(5856)
                        },
                        new
                        {
                            Id = new Guid("ee0c8986-7a27-4685-9c4d-05c5fe9f41f4"),
                            Author = "Anas",
                            Description = "More Spookier",
                            Genre = "Spooky",
                            IsLoanAble = true,
                            Title = "Spooky Book 2",
                            Year = new DateTime(2023, 9, 13, 18, 56, 21, 929, DateTimeKind.Local).AddTicks(5922)
                        },
                        new
                        {
                            Id = new Guid("07aaa680-382e-4a9f-a8c5-e9c3d40b2b66"),
                            Author = "Lucas",
                            Description = "Very Spy",
                            Genre = "Spy",
                            IsLoanAble = false,
                            Title = "Bames Jond",
                            Year = new DateTime(2023, 9, 13, 18, 56, 21, 929, DateTimeKind.Local).AddTicks(5927)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
